// Catálogo maestro de tipos de proceso de planta.
// Cada tipo tiene su lista de subprocesos (PROC) con su tiempo estimado en minutos.
// Esta es la fuente de verdad para armar el checklist dinámico al crear un proceso.

const procesosPlanta = {
  "Union vulcanizado": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "SUAJE", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "VULCANIZADO", tiempoEstimado: 45 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Union grapado": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "GRAPADO", tiempoEstimado: 20 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Tramo abierto": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "MANIOBRA", tiempoEstimado: 10 },
    { proc: "CORTE", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Union biselado": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "BISELADO", tiempoEstimado: 20 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "VULCANIZADO", tiempoEstimado: 40 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Banda para servicio": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "SUAJE", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "ENCINTADO", tiempoEstimado: 20 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Banda modular": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "PATRON DE MEDIDA EN ANCHO", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "ARMADO DE BANDA", tiempoEstimado: 30 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Union con guia": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "PREPARACION PEGADO DE GUIA", tiempoEstimado: 15 },
    { proc: "UNION", tiempoEstimado: 30 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "PEGADO DE GUIA", tiempoEstimado: 20 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Empujadores BL": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "MARCAR DISTRIBUCION DE EMPUJADORES", tiempoEstimado: 15 },
    { proc: "PEGADO DE EMPUJADORES", tiempoEstimado: 25 },
    { proc: "UNION", tiempoEstimado: 30 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "MARCAR DISTRIBUCION DE EMPUJADORES", tiempoEstimado: 10 },
    { proc: "PEGADO DE EMPUJADORES", tiempoEstimado: 20 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Empujadores BP": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "MARCAR DISTRIBUCION DE EMPUJADORES", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "CORTE Y DECAPADO DE EMPUJADORES", tiempoEstimado: 20 },
    { proc: "PERFORAR EMPUJADORES Y MARCARLOS EN BANDA", tiempoEstimado: 25 },
    { proc: "INSPECCIÓN 3", tiempoEstimado: 5 },
    { proc: "PERFORAR BANDA", tiempoEstimado: 20 },
    { proc: "FIJAR EMPUJADORES Y CORTAR SOBRENTE", tiempoEstimado: 30 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Perforada union": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "PERFORACIONES", tiempoEstimado: 20 },
    { proc: "PREPARACION PEGADO DE GUIA", tiempoEstimado: 15 },
    { proc: "UNION", tiempoEstimado: 30 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "PEGADO DE GUIA", tiempoEstimado: 20 },
    { proc: "MEDICIÓN Y LIMPIEZA", tiempoEstimado: 10 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
  "Banda curva": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "REVISION DE ANGULOS Y CORTE", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 1 DIMENSIONAL", tiempoEstimado: 5 },
    { proc: "SUAJE", tiempoEstimado: 15 },
    { proc: "VULCANIZADO", tiempoEstimado: 45 },
    { proc: "INSPECCIÓN 2", tiempoEstimado: 5 },
    { proc: "PERFORACIONES Y REMACHES", tiempoEstimado: 25 },
    { proc: "INSPECCIÓN FINAL", tiempoEstimado: 5 },
  ],
  "Banda monolitica": [
    { proc: "SURTIDO", tiempoEstimado: 5 },
    { proc: "CORTE", tiempoEstimado: 10 },
    { proc: "SUAJE", tiempoEstimado: 15 },
    { proc: "INSPECCIÓN 1", tiempoEstimado: 5 },
    { proc: "ENCINTADO", tiempoEstimado: 20 },
    { proc: "ETIQUETADO", tiempoEstimado: 2 },
  ],
};

// Suma de los tiempos estimados (en minutos) de todos los subprocesos de un tipo.
export function tiempoEstimadoTotalMin(tipo) {
  return (procesosPlanta[tipo] || []).reduce((acc, s) => acc + s.tiempoEstimado, 0);
}

export default procesosPlanta;
